### ISSUE TITLE
Error when doing a Confirm Intent Payment on Angular Intent Demo

### ISSUE THREAD

**Issue by jlbuganan** [triniwiz/nativescript-stripe#110]
### Which platform(s) does your issue occur on?
- Simulator; iOS 13.4

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.5.0
- Cross-platform modules:  6.2.3
- Runtime(s): 6.2.0
- Plugin(s): latest version

### Please, tell us how to recreate the issue in as much detail as possible. 
1. Followed all instructions for the Angular demo. Entered a valid publishable API key, created a backend on herokuapp.
2. Click Intent to get to the Intent Integration demo.
3. Enter 4242 4242 4242 4242 as the example credit card, random numbers for the rest of the fields.
4. Click "Automatic Confirm Intent Payment (12$)" or "Manual Confirm Intent Payment (12$)"
5. I receive an error in the console (see below).

### Error
`Unhandled Promise rejection: <h1>Not Found</h1> ; Zone: <root> ; Task: Promise.then ; Value: Error: <h1>Not Found</h1> at file: app/demo/stripe.service.ts:98:24 [<root>]
at file: node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:883:0 [<root>]
at drainMicroTaskQueue(file: node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:595:0) [<root>]
at promiseReactionJob([native code]) [<root>]
at UIApplicationMain([native code]) [<root>]
at _start(file: node_modules/@nativescript/core/application/application.ios.js:324:0) [<root>]
at run(file: node_modules/@nativescript/core/application/application.ios.js:366:0) [<root>]
at bootstrapNativeScriptApp(file: node_modules/nativescript-angular/platform-common.js:205:0) [<root>]
at bootstrapApp(file: node_modules/nativescript-angular/platform-common.js:106:0) [<root>]
at bootstrapModule(file: node_modules/nativescript-angular/platform-common.js:90:0) [<root>]
at file:///app/bundle.js:2097:144 [<root>]
at ./main.ts(file:///app/bundle.js:2102:34) [<root>]
at __webpack_require__(file: app/webpack/bootstrap:750:0) [<root>]
at checkDeferredModules(file: app/webpack/bootstrap:43:0) [<root>]
at webpackJsonpCallback(file: app/webpack/bootstrap:30:0) [<root>]
at anonymous(file:///app/bundle.js<…>
`

**Comment by RobertGardner** [comment]
It looks like Stripe changed their example backend. I'm working on updating `demo-angular` to work with the new backend, but it's going slower than I expected.

In the meantime, you can use `https://ns-stripe-example-backend.herokuapp.com/` for the `backendBaseURL` and intents should work. If you need to see the old backend code that is used by `ns-stripe-backend` you can check out the [Stripe example backend](https://github.com/stripe/example-mobile-backend) `web.rb` history and look just before the commit labeled "Update to match docs".

**Comment by jlbuganan** [comment]
Thank you. In the meantime, I was able to get what I needed in my own implementation by changing a couple of the endpoints in stripe.service.ts:

`confirm_payment` to `confirm_payment_intent`
`create_intent` to `create_payment_intent`

**Comment by RobertGardner** [comment]
The `demo-angular` app has now been updated to work correctly with the latest Stripe example backend.

See 99affa184a53b698116baf50847f2cd89c111ab8
